
services:
    irods-server:
      container_name: irods-server
      image: "ghcr.io/wtsi-npg/ub-16.04-irods-4.2.7:latest"
      platform: linux/amd64
      ports:
        - "127.0.0.1:1247:1247"
        - "127.0.0.1:20000-20199:20000-20199"
      restart: always
      healthcheck:
        test: ["CMD", "nc", "-z", "-v", "127.0.0.1", "1247"]
        start_period: 30s
        interval: 5s
        timeout: 10s
        retries: 12

    app:
      build:
        context: .
        dockerfile: Dockerfile
      command: ["start",
                "--host", "0.0.0.0",
                "--port", "3333",
                "--cert-file", "/app/config/localhost.crt",
                "--key-file", "/app/config/localhost.key",
                "--irods-env", "/app/config/app_irods_environment.json",
                "--enable-oidc",
                "--index-interval", "60s",
                "--log-level", "trace"]
      # Set the following environment variables in a .env file (files named .env
      # are declared in .gitignore):
      #
      # If no iRODS auth file is provided:
      #
      # IRODS_PASSWORD
      #
      # And if using OIDC:
      #
      # OIDC_CLIENT_ID
      # OIDC_CLIENT_SECRET
      # OIDC_ISSUER_URL
      # OIDC_CALLBACK_URL
      env_file: .env
      ports:
        - "3333:3333"
      volumes:
        - ./server/testdata/config:/app/config
      depends_on:
        irods-server:
          condition: service_healthy
