version: "3"

services:
  irods-server:
    container_name: irods-server
    image: "ghcr.io/wtsi-npg/ub-16.04-irods-4.2.7:latest"
    ports:
      - "127.0.0.1:1247:1247"
      - "127.0.0.1:20000-20199:20000-20199"
    restart: always

  app:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3333:3333"
    depends_on:
      - irods-server
