Host = "0.0.0.0"
Port  = "3333"
IRODSEnvFilePath = "/app/config/app_irods_environment.json"
CertFilePath = "/app/config/localhost.crt"
KeyFilePath = "/app/config/localhost.key"
EnableOIDC  = true
OIDCClientID = "0oafha8j3cQCmfxRP417"
OIDCClientSecret = "pjDn3100j2eJaqg9uOYYZ3uDkHdHHQI9ku4Nkn9vx_6twZELwA_euVQeIg3iyVoJ"
OIDCIssuerURL = ""
OIDCRedirectURL = ""
IndexInterval = "60s"
